version: '3.7'
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgreshkn}
            PGDATA: /data/postgres
            DB_HOST: 127.0.0.1
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - postgres
    nginx:
        build: nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
            - ../:/var/www/symfony
networks:
    postgres:
        driver: bridge
volumes:
    nginx:
    php:
    postgres:
