version: '3.7'
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgreshkn}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-blt-hkn@hotmail.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadminhkn}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - postgres
        restart: unless-stopped
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - postgres
    nginx:
        build: nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
networks:
    postgres:
        driver: bridge
volumes:
    nginx:
    php:
    postgres:
    pgadmin: