version: '3.7'
services:
    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            DB_HOST: 127.0.0.1
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
        restart: always
    php:
        build: docker/php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ./:/var/www/symfony:cached
            - ./docker/logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - db
    nginx:
        build: docker/nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx:cached
            - ./:/var/www/symfony
        depends_on:
            - php
volumes:
    db-data: {}
